// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"time"
)

type Account struct {
	Id          *string         `json:"Id,omitempty" bson:"_id"`
	Name        *string         `json:"Name,omitempty"`
	PhoneNumber *string         `json:"PhoneNumber,omitempty"`
	Email       *string         `json:"Email,omitempty"`
	Currency    *string         `json:"Currency,omitempty"`
	Balance     *int            `json:"Balance,omitempty"`
	Active      *bool           `json:"Active,omitempty"`
	Address     *AccountAddress `json:"Address,omitempty"`
}

type AccountAddress struct {
	Type               *string `json:"Type,omitempty"`
	CareOf             *string `json:"CareOf,omitempty"`
	Department         *string `json:"Department,omitempty"`
	SubDepartment      *string `json:"SubDepartment,omitempty"`
	StreetName         *string `json:"StreetName,omitempty"`
	BuildingNumber     *string `json:"BuildingNumber,omitempty"`
	BuildingName       *string `json:"BuildingName,omitempty"`
	Floor              *string `json:"Floor,omitempty"`
	UnitNumber         *string `json:"UnitNumber,omitempty"`
	PostBox            *string `json:"PostBox,omitempty"`
	Room               *string `json:"Room,omitempty"`
	PostalCode         *string `json:"PostalCode,omitempty"`
	TownName           *string `json:"TownName,omitempty"`
	TownLocationName   *string `json:"TownLocationName,omitempty"`
	DistrictName       *string `json:"DistrictName,omitempty"`
	CountrySubdivision *string `json:"CountrySubdivision,omitempty"`
	Country            *string `json:"Country,omitempty"`
	AddressLine        *string `json:"AddressLine,omitempty"`
}

type Bank struct {
	Id       *string   `json:"Id,omitempty" bson:"_id"`
	Name     *string   `json:"Name,omitempty"`
	Bic      *string   `json:"BIC,omitempty"`
	Country  *string   `json:"Country,omitempty"`
	Balance  *int      `json:"Balance,omitempty"`
	Active   *bool     `json:"Active,omitempty"`
	Branches []*Branch `json:"Branches,omitempty"`
}

type Branch struct {
	Id          *string         `json:"Id,omitempty"`
	Name        *string         `json:"Name,omitempty"`
	PhoneNumber *string         `json:"PhoneNumber,omitempty"`
	Address     *AccountAddress `json:"Address,omitempty"`
}

type EventLog struct {
	Id             *string    `json:"Id,omitempty" bson:"_id"`
	ReqId          *string    `json:"ReqId,omitempty"`
	EntityId       *string    `json:"EntityId,omitempty"`
	EventDate      *time.Time `json:"EventDate,omitempty"`
	EventID        *string    `json:"EventId,omitempty"`
	EventRemark    *string    `json:"EventRemark,omitempty"`
	AdditionalInfo *string    `json:"AdditionalInfo,omitempty"`
	Errors         []*string  `json:"Errors,omitempty"`
}

type Query struct {
}
