package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"payment-simulator/internal/db"
	"payment-simulator/internal/routing/graphql/graph/gqlmodel"

	"go.mongodb.org/mongo-driver/bson"
)

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*gqlmodel.Account, error) {
	cursor, _ := db.DB.Collection("Accounts").Find(ctx, bson.M{})
	var accounts []*gqlmodel.Account
	cursor.All(ctx, &accounts)
	return accounts, nil
}

// Eventlog is the resolver for the eventlog field.
func (r *queryResolver) Eventlog(ctx context.Context, entityID string) ([]*gqlmodel.EventLog, error) {
	cursor, _ := db.DB.Collection("EventLog").Find(ctx, bson.M{"entityid": entityID})
	var events []*gqlmodel.EventLog
	cursor.All(ctx, &events)
	return events, nil
}

// Banks is the resolver for the banks field.
func (r *queryResolver) Banks(ctx context.Context) ([]*gqlmodel.Bank, error) {
	cursor, _ := db.DB.Collection("Banks").Find(ctx, bson.M{})
	var banks []*gqlmodel.Bank
	cursor.All(ctx, &banks)
	return banks, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
